name: Deploy to Cloud Foundry

on: [push]
    
jobs: 
  deploy:
    runs-on: ubuntu-18.04
    
    steps:
    - uses: citizen-of-planet-earth/cf-cli-action@master
      with:
        cf_api: https://api.cloud.pcftest.com
        cf_username: ${{ secrets.CF_USER }}
        cf_password: ${{ secrets.CF_PASSWORD }}
        cf_org: client-src-ampm
        cf_space: dev-infra
        command: cf push -f ./manifest.yml
