name: Deploy to Cloud Foundry

on: [push]
    
jobs: 
  deploy:
    runs-on: ubuntu-18.04
    
    steps:
    - uses: citizen-of-planet-earth/cf-cli-action@master
      with:
        cf_login: cf8 login -a https://api.cloud.pcftest.com -u ${{ secrets.CF_USER }} -p ${{ secrets.CF_PASSWORD }}
        cf_api: https://api.cloud.pcftest.com
        cf_org: client-src-ampm
        cf_space: dev-infra
        command: cf8 push -f ./manifest.yml
